name: CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
 sync-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: hhyasdf/image-sync-action@v1.1
        with:
          auth_file: ./auth.yaml
          images_file: ./images.yaml
          version: latest
          proc: 20
        env:
          ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
          ACR_USER: "${{ secrets.ACR_USER }}"
